development:
  adapter: postgresql
  encoding: unicode
  database: humanitywar-rails_development
  pool: 5
  host: localhost
  username: vosechu
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: humanitywar-rails_test
  pool: 5
  host: localhost
  username: vosechu
  password: